- name: copy catalogue service
  ansible.builtin.copy:
    src: catalogue.service
    dest: /etc/systemd/system/catalogue.service
  notify: deamon reload

- name: daemon reload enable and start
  ansible.builtin.systemd_service:
    name: catalogue
    enabled: true
    state: restarted